# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"colorbuddy.nvim" = "scm"
"lir.nvim" = "scm"
"mini.nvim" = "scm"
"rocks-git.nvim" = "2.5.3"
"rocks.nvim" = "2.45.0"
"typescript-tools.nvim" = "scm"
fzf-lua = "0.0.1902"
nvim-dap = "scm"
nvim-dap-ui = "scm"
nvim-lspconfig = "2.1.0"
nvim-spider = "scm"

[plugins."neosolarized.nvim"]
git = "svrana/neosolarized.nvim"
rev = "main"

[plugins.nvim-highlight-colors]
git = "brenoprata10/nvim-highlight-colors"
rev = "main"

[plugins."reply.vim"]
git = "rhysd/reply.vim"
rev = "master"

[plugins."tint.nvim"]
git = "lbrayner/tint.nvim"
rev = "80b15a91087991068d5834419437f652d1d4bc8e"
branch = "fixes"
ignore_tags = true

[plugins.nvim-jdtls]
git = "lbrayner/nvim-jdtls"
rev = "lbrayner"

[plugins.vim-characterize]
git = "tpope/vim-characterize"
rev = "master"

[plugins.vim-dadbod]
git = "tpope/vim-dadbod"
rev = "e95afed23712f969f83b4857a24cf9d59114c2e6"
branch = "master"
ignore_tags = true

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
rev = "master"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "master"

[plugins.vim-obsession]
git = "tpope/vim-obsession"
rev = "master"

[plugins.vim-quickhl]
git = "t9md/vim-quickhl"
rev = "master"

[plugins.vim-rsi]
git = "tpope/vim-rsi"
rev = "master"

[plugins.vim-rzip]
git = "lbrayner/vim-rzip"
rev = "master"
