# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"colorbuddy.nvim" = "scm"
"lir.nvim" = "scm"
"mini.nvim" = "scm"
"rocks-git.nvim" = "2.6.0"
"rocks.nvim" = "2.49.0"
"typescript-tools.nvim" = "scm"
nvim-dap = "scm"
nvim-lspconfig = "2.11.0"
nvim-spider = "scm"

[plugins."neosolarized.nvim"]
git = "svrana/neosolarized.nvim"
rev = "0c01fd2ac2ab33918073f57c63bcb2ae5a31d8de"
branch = "main"
ignore_tags = true

[plugins.nvim-dap-view]
git = "igorlfs/nvim-dap-view"
rev = "4e73e57008df10f9971b60c3a11e6aa11ba9f94a"
branch = "main"
ignore_tags = true

[plugins.nvim-fzf]
git = "lbrayner/nvim-fzf"
rev = "7b2bc051b31dbddd8ce97a55666952f5322099a4"
branch = "lbrayner"
ignore_tags = true

[plugins.nvim-highlight-colors]
git = "brenoprata10/nvim-highlight-colors"
rev = "e4c7af0211866162d999ce0bdd6a029302e19139"
branch = "main"
ignore_tags = true

[plugins."reply.vim"]
git = "rhysd/reply.vim"
rev = "f458f7c13cbd8eafaf9acd69e8eade71416338c5"
branch = "master"
ignore_tags = true

[plugins."tint.nvim"]
git = "lbrayner/tint.nvim"
rev = "fixes"
ignore_tags = true

[plugins.nvim-jdtls]
git = "lbrayner/nvim-jdtls"
rev = "77ccaeb422f8c81b647605da5ddb4a7f725cda90"
ignore_tags = true

[plugins.vim-characterize]
git = "tpope/vim-characterize"
rev = "a8bffac6cead6b2869d939ecad06312b187a4c79"
branch = "master"
ignore_tags = true

[plugins.vim-dadbod]
git = "tpope/vim-dadbod"
rev = "6d1d41da4873a445c5605f2005ad2c68c99d8770"
branch = "master"
ignore_tags = true

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
rev = "929490937745cd96130d3e7948f762f0aa403314"
branch = "master"
ignore_tags = true

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0"
branch = "master"
ignore_tags = true

[plugins.vim-obsession]
git = "tpope/vim-obsession"
rev = "ed9dfc7c2cc917ace8b24f4f9f80a91e05614b63"
branch = "master"
ignore_tags = true

[plugins.vim-quickhl]
git = "t9md/vim-quickhl"
rev = "be1f44169c3fdee3beab629e83380515da03835e"
branch = "master"
ignore_tags = true

[plugins.vim-rsi]
git = "tpope/vim-rsi"
rev = "45540637ead22f011e8215f1c90142e49d946a54"
branch = "master"
ignore_tags = true

[plugins.vim-rzip]
git = "lbrayner/vim-rzip"
rev = "f65400fed27b27c7cff7ef8d428c4e5ff749bf28"
branch = "master"
ignore_tags = true
