# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"colorbuddy.nvim" = "scm"
"lir.nvim" = "scm"
"mini.nvim" = "scm"
"rocks-git.nvim" = "2.5.3"
"rocks.nvim" = "2.45.0"
"typescript-tools.nvim" = "scm"
fzf-lua = "0.0.1952"
nvim-dap = "scm"
nvim-dap-ui = "scm"
nvim-lspconfig = "2.3.0"
nvim-spider = "scm"

[plugins."neosolarized.nvim"]
git = "svrana/neosolarized.nvim"
branch = "main"
rev = "0c01fd2ac2ab33918073f57c63bcb2ae5a31d8de"
ignore_tags = true

[plugins.nvim-highlight-colors]
git = "brenoprata10/nvim-highlight-colors"
branch = "main"
rev = "b42a5ccec7457b44e89f7ed3b3afb1b375bb2093"
ignore_tags = true

[plugins."reply.vim"]
git = "rhysd/reply.vim"
branch = "master"
rev = "f458f7c13cbd8eafaf9acd69e8eade71416338c5"
ignore_tags = true

[plugins."tint.nvim"]
git = "lbrayner/tint.nvim"
rev = "fixes"
ignore_tags = true

[plugins.nvim-jdtls]
git = "lbrayner/nvim-jdtls"
branch = "lbrayner"
rev = "8597d57fb40d4ad503cf3acb2fdcfe1b0d8a193d"
ignore_tags = true

[plugins.vim-characterize]
git = "tpope/vim-characterize"
branch = "master"
rev = "a8bffac6cead6b2869d939ecad06312b187a4c79"
ignore_tags = true

[plugins.vim-dadbod]
git = "tpope/vim-dadbod"
branch = "master"
rev = "e95afed23712f969f83b4857a24cf9d59114c2e6"
ignore_tags = true

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
branch = "master"
rev = "e86bb794a1c10a2edac130feb0ea590a00d03f1e"
ignore_tags = true

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
branch = "master"
rev = "593f831d6f6d779cbabb70a4d1e6b1b1936a88af"
ignore_tags = true

[plugins.vim-obsession]
git = "tpope/vim-obsession"
branch = "master"
rev = "ed9dfc7c2cc917ace8b24f4f9f80a91e05614b63"
ignore_tags = true

[plugins.vim-quickhl]
git = "t9md/vim-quickhl"
branch = "master"
rev = "be1f44169c3fdee3beab629e83380515da03835e"
ignore_tags = true

[plugins.vim-rsi]
git = "tpope/vim-rsi"
branch = "master"
rev = "45540637ead22f011e8215f1c90142e49d946a54"
ignore_tags = true

[plugins.vim-rzip]
git = "lbrayner/vim-rzip"
branch = "master"
rev = "f65400fed27b27c7cff7ef8d428c4e5ff749bf28"
ignore_tags = true
