# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"colorbuddy.nvim" = "scm"
"lir.nvim" = "scm"
"mini.nvim" = "scm"
"nvim-colorizer.lua" = "scm"
"rocks-git.nvim" = "2.3.1"
"rocks.nvim" = "2.40.2"
"typescript-tools.nvim" = "scm"
fzf-lua = "0.0.1458"
nvim-dap-ui = "scm"
nvim-lspconfig = "1.0.0"
nvim-snippy = "scm"
nvim-spider = "scm"

[plugins."neosolarized.nvim"]
git = "svrana/neosolarized.nvim"
rev = "main"

[plugins."tint.nvim"]
git = "lbrayner/tint.nvim"
rev = "fixes"

[plugins.nvim-jdtls]
git = "lbrayner/nvim-jdtls"
rev = "lbrayner"

[plugins.vim-characterize]
git = "tpope/vim-characterize"
rev = "master"

[plugins.vim-dadbod]
git = "tpope/vim-dadbod"
rev = "master"

[plugins.vim-rsi]
git = "tpope/vim-rsi"
rev = "master"
